main: main.cpp fileio.hpp fileio.cpp dbg.hpp util.cpp util.hpp ScrollWin.hpp Win.hpp SelectionList.hpp UI.hpp FileBrowser.hpp
	g++ -o main main.cpp fileio.cpp util.cpp -lcurses -std=c++17 -g

test: test.cpp fileio.hpp fileio.cpp dbg.hpp util.hpp
	g++ -o test test.cpp fileio.cpp -lcurses